tests a function the multiplies two matrixes
============================================

>>> lazy_matrix_mul = __import__("101-lazy_matrix_mul").lazy_matrix_mul
>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
array([[ 7, 10],
       [15, 22]])
>>> lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]])
array([[13, 16]])

tests with invalid args
-----------------------
>>> lazy_matrix_mul("not a list", [[1, 2], [3, 4]])
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> lazy_matrix_mul([[1, 2], [3, 4]], "not a list")
Traceback (most recent call last):
ValueError: Scalar operands are not allowed, use '*' instead

>>> lazy_matrix_mul([1, 2], [[8, 6]])
Traceback (most recent call last):
ValueError: shapes (2,) and (1,2) not aligned: 2 (dim 0) != 1 (dim 0)

>>> lazy_matrix_mul([], [[1, 2], [3, 4]])
Traceback (most recent call last):
ValueError: shapes (0,) and (2,2) not aligned: 0 (dim 0) != 2 (dim 0)

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[]])
Traceback (most recent call last):
ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([[2, 'b'], [5, 3]], [[1, 2], [3, 4]])
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, [1]], [2, 3]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> lazy_matrix_mul([[1, 2], [1, 2, 3]], [[1, 2], [3, 4]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4, 5]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.
